[package]
name = "json-stream"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.2"
serde_json = "1.0.12"
serde_derive = "1.0.33"
serde = "1.0.33"
